name: Auto-PR to Playstore

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create PR to Playstore
      uses: peter-evans/create-pull-request@v5
      with:
        branch: playstore
        title: (CD) Sync Playstore with Main
        commit-message: Automatic PR from main
        body: |
          This is an automatic pull request created by GitHub Actions.
